apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: spring-4624 
  janus-idp.io/tekton: spring-4624
  backstage.io/kubernetes-id: spring-4624
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: spring-4624
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  